---
title: "Project-Code"
author: "Dennis Goldenberg"
date: "2024-11-27"
output: pdf_document
---
# Predicting CAT Bond Market Yield Performance using Time Series Data
```{r, include = TRUE}
library(readxl)
suppressWarnings(library(quantmod))
suppressWarnings(library(ggplot2))
```

## Reading in Data
```{r, include = TRUE}
yield_w_EL <- read_xlsx(path = "data/yield_with_EL.xlsx",
                        skip = 2)
credit_spread <- read_xls(path = "data/Credit_Spread_BofA.xls",
                          skip = 10)

yield_w_EL$Date <- as.Date(yield_w_EL$Date)
credit_spread$observation_date <- as.Date(credit_spread$observation_date)
colnames(credit_spread) <- c("Date", "Spread")
yield_w_EL
```

```{r, include = TRUE}
S_and_P <- read_xls(path = "data/SP500.xls",
                    skip = 10)
S_and_P$observation_date <- as.Date(S_and_P$observation_date)
colnames(S_and_P) <- c("Date", "SP500")
S_and_P
```


```{r, include = TRUE}
monthlyReturn(S_and_P)
```

```{r, include = TRUE}
ggplot(data = yield_w_EL) + geom_line(aes(x = Date,
                                          y = `Total Coupon CAT Bond Market (USD)`))
```

```{r, include = TRUE}
S_and_P$SP500 <- S_and_P$SP500/S_and_P$SP500[1]
ggplot(data = S_and_P) + geom_line(aes(x = Date,
                                       y = SP500))
```


```{r, include = TRUE}
S_and_P_daily <- read_xls(path = "data/SP500_daily.xls",
                    skip = 10)
S_and_P_daily$observation_date <- as.Date(S_and_P_daily$observation_date)
colnames(S_and_P_daily) <- c("Date", "SP500_daily")
weekly_returns <- weeklyReturn(S_and_P_daily)
```

```{r, include = TRUE}
week_S_and_P <- list(S_and_P$Date, weekly_returns$weekly.returns[-1])
week_S_and_P <- as.data.frame(week_S_and_P)
colnames(week_S_and_P) <- c("Date", "returns")
rownames(week_S_and_P) <- seq(1:dim(week_S_and_P)[1])
#ggplot(data = week_S_and_P) + geom_line(aes(x = Date, y = returns))
```

```{r, include = TRUE}
S_and_P_daily
```

```{r}
EAFE <- read.csv("data/EAFE International Index value.csv")
EAFE
```